DROP TABLE ready.t_detections;

CREATE TABLE IF NOT EXISTS ready.t_detections (
    ID BIGINT AUTO_INCREMENT,
    DETECTION_TIME VARCHAR(300) NOT NULL,
    HEIGHT DOUBLE NOT NULL,
    DISTANCE DOUBLE NOT NULL,
    IS_OURS BOOLEAN,
    IS_SHUTDOWN BOOLEAN,
    IMAGE_URL VARCHAR(300) NOT NULL,
    PRIMARY KEY (ID)
);